export const GET_DEMO_REQUEST = 'GET_DEMO_REQUEST';
export const GET_DEMO_SUCCESS = 'GET_DEMO_SUCCESS';
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR';
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE';
